name: Testing

on:
  push:
    branches: [ main, dev, feature/* ]
  pull_request:
    branches: [ main ]


jobs:

  test:
    strategy:
      max-parallel: 6
      matrix:
        go-version: [ 1.23, 1.24 ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Install Go on the Container
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test the Go code
        run: go test -v ./...